// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsypsxpqeulygyrmzndn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeXBzeHBxZXVseWd5cm16bmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTY1MzIsImV4cCI6MjA2ODkzMjUzMn0.8mfvs8_OO0Zy9s5nTR5WLrLwlGv4ZKOu3K5O06bKMAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});